const bannerTypes = {
  CHALLENGE_OF_THE_DAY: 'CHALLENGE_OF_THE_DAY',
  EXPLORE: 'EXPLORE',
  POPULAR_CHALLENGE: 'POPULAR_CHALLENGE',
  CHALLENGE: 'CHALLENGE'
};
const exploreCategory = {
  GOOGLE_CALENDER_REMINDERS: 'GOOGLE_CALENDER_REMINDERS',
  SURPRISE_ME: 'SURPRISE_ME',
  EXTERNAL_LINK_BANNER: 'EXTERNAL_LINK_BANNER',
  INTERNAL_LINK_BANNER: 'INTERNAL_LINK_BANNER',
};
module.exports = {
  bannerTypes,
  exploreCategory,
};
